version: "3"

services:
  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - default
    restart: always
    volumes:
      - ./tmp:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: app
    restart: always
    volumes:
      - .:/app
      - ./client/build:/app/public
    ports:
      - 3333:3333
    networks:
      - default
    links:
      - mysql

networks:
  default:
    driver: bridge
